// <auto-generated />
using EasyMaster.Model.RPG;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyMaster.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250409000233_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyMaster.Model.RPG.Componente", b =>
                {
                    b.Property<int>("IdComponente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComponente"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdModulo")
                        .HasColumnType("int");

                    b.Property<int>("ModuloIdModulo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdComponente");

                    b.HasIndex("ModuloIdModulo");

                    b.ToTable("Componentes");
                });

            modelBuilder.Entity("EasyMaster.Model.RPG.Modulo", b =>
                {
                    b.Property<int>("IdModulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModulo"));

                    b.Property<int>("IdSistema")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonagemIdPersonagem")
                        .HasColumnType("int");

                    b.Property<int>("SistemaIdSistema")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdModulo");

                    b.HasIndex("PersonagemIdPersonagem");

                    b.HasIndex("SistemaIdSistema");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("EasyMaster.Model.RPG.Personagem", b =>
                {
                    b.Property<int>("IdPersonagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersonagem"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdSistema")
                        .HasColumnType("int");

                    b.Property<string>("Lore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SistemaIdSistema")
                        .HasColumnType("int");

                    b.HasKey("IdPersonagem");

                    b.HasIndex("SistemaIdSistema");

                    b.ToTable("Personagens");
                });

            modelBuilder.Entity("EasyMaster.Model.RPG.Sistema", b =>
                {
                    b.Property<int>("IdSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSistema"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSistema");

                    b.ToTable("Sistemas");
                });

            modelBuilder.Entity("EasyMaster.Model.RPG.Componente", b =>
                {
                    b.HasOne("EasyMaster.Model.RPG.Modulo", "Modulo")
                        .WithMany("Componentes")
                        .HasForeignKey("ModuloIdModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("EasyMaster.Model.RPG.Modulo", b =>
                {
                    b.HasOne("EasyMaster.Model.RPG.Personagem", null)
                        .WithMany("Modulos")
                        .HasForeignKey("PersonagemIdPersonagem");

                    b.HasOne("EasyMaster.Model.RPG.Sistema", "Sistema")
                        .WithMany("Modulos")
                        .HasForeignKey("SistemaIdSistema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("EasyMaster.Model.RPG.Personagem", b =>
                {
                    b.HasOne("EasyMaster.Model.RPG.Sistema", "Sistema")
                        .WithMany("Personagens")
                        .HasForeignKey("SistemaIdSistema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("EasyMaster.Model.RPG.Modulo", b =>
                {
                    b.Navigation("Componentes");
                });

            modelBuilder.Entity("EasyMaster.Model.RPG.Personagem", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("EasyMaster.Model.RPG.Sistema", b =>
                {
                    b.Navigation("Modulos");

                    b.Navigation("Personagens");
                });
#pragma warning restore 612, 618
        }
    }
}
